#:import Graph kivy.garden.graph.Graph
<GraphDemo>:
    orientation: 'vertical'

    Graph:
        id: graph_plot
        background_color: (0.5, 0.5, 0.5, 1)
        xlabel: 't'
        ylabel: 'accelerometer'
        x_grid: True
        y_grid: True
        x_grid_label: True
        y_grid_label: True
        x_ticks_minor: 5
        x_ticks_major: 25
        ymin: 0
        ymax: 10
        y_ticks_major: 1

    ToggleButton:
        id: toggle_button
        on_release: root.do_toggle()
        text: 'Start Accelerometer'
        size_hint: 1, None
        height: self.texture_size[1] * 5